
import { Jost } from 'next/font/google'
import "./global.css"

const jost = Jost({
  weight: ["700", "500", "800"],
  style: ["normal"],
  subsets: ["latin"]
})

export const metadata = {
  title: 'Own Sushi App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='manifest' href='/manifest.json' />
      </head>
      <body className={jost.className}>
        {children}
      </body>
    </html>
  )
}
